import type { ProfessionalProfile, FounderProfile, Project, GovernanceLog, SurveyQuestion, User, Contract, ContractTemplate, Application, ActivityLog, Message, CompanyProfile, RoadmapPhase } from './types';

export const DUMMY_FOUNDERS: FounderProfile[] = [
    {
      "id": "f001",
      "name": "Sarah Chen",
      "company": "TechFlow AI",
      "stage": "Pre-Seed",
      "industry": "AI/ML",
      "location": "Tulsa, OK",
      "description": "Building AI-powered workflow automation for small businesses. Our platform integrates with existing tools to streamline repetitive tasks, saving businesses an average of 15 hours per week. We are seeking a technical co-founder with deep ML expertise to lead our product development.",
      "equity_offered": "15-20%",
      "vesting": "4 years, 1 year cliff",
      "funding_raised": "$0",
      "team_size": 2,
      "revenue": "Pre-revenue",
      "looking_for": ["CTO", "Lead Engineer", "ML Specialist"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f001",
      "rating": 4.8
    },
    {
      "id": "f002",
      "name": "Marcus Johnson",
      "company": "EcoLogistics",
      "stage": "Seed",
      "industry": "GreenTech",
      "location": "Tulsa, OK",
      "description": "A sustainable delivery optimization platform that helps e-commerce businesses reduce their carbon footprint. Our algorithm optimizes delivery routes for efficiency and environmental impact. We have early traction and are looking for marketing and business development talent to scale our growth.",
      "equity_offered": "8-12%",
      "vesting": "4 years, 1 year cliff",
      "funding_raised": "$150K",
      "team_size": 4,
      "revenue": "$8K MRR",
      "looking_for": ["VP Marketing", "Business Development", "UX Designer"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f002",
      "rating": 4.6
    },
    {
      "id": "f003",
      "name": "Dr. Priya Patel",
      "company": "MedConnect",
      "stage": "Pre-Seed",
      "industry": "HealthTech",
      "location": "Tulsa, OK",
      "description": "A HIPAA-compliant telemedicine platform designed to connect patients in rural communities with specialist doctors. We aim to bridge the healthcare gap by providing accessible and affordable virtual consultations. We need technical and regulatory expertise to navigate the complex healthcare landscape.",
      "equity_offered": "10-15%",
      "vesting": "4 years, 6 month cliff",
      "funding_raised": "$25K",
      "team_size": 3,
      "revenue": "Pre-revenue",
      "looking_for": ["Full-Stack Developer", "Regulatory Consultant", "Product Manager"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f003",
      "rating": 4.9
    },
    {
      "id": "f004",
      "name": "James Lee",
      "company": "FinSecure",
      "stage": "Seed",
      "industry": "FinTech",
      "location": "Austin, TX",
      "description": "A decentralized finance (DeFi) platform making crypto lending and borrowing secure and accessible to everyone. We've completed our seed round and are looking to build out our core engineering team.",
      "equity_offered": "5-8%",
      "vesting": "4 years, 1 year cliff",
      "funding_raised": "$500K",
      "team_size": 5,
      "revenue": "$2K MRR",
      "looking_for": ["Lead Engineer", "Smart Contract Developer", "DevOps"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f004",
      "rating": 4.7
    },
    {
      "id": "f005",
      "name": "Chloe Kim",
      "company": "StyleBox",
      "stage": "Pre-Seed",
      "industry": "E-commerce",
      "location": "Remote",
      "description": "An AI-powered personal styling subscription service for men and women. We're in the MVP phase and need a marketing co-founder to help us build a brand and acquire our first users.",
      "equity_offered": "10-18%",
      "vesting": "4 years, 6 month cliff",
      "funding_raised": "$50K",
      "team_size": 2,
      "revenue": "Pre-revenue",
      "looking_for": ["VP Marketing", "Content Strategy", "UX Designer"],
      "verified": false,
      "avatar": "https://i.pravatar.cc/150?u=f005",
      "rating": 4.5
    },
    {
      "id": "f006",
      "name": "Ben Carter",
      "company": "LearnSphere",
      "stage": "Seed",
      "industry": "EdTech",
      "location": "Tulsa, OK",
      "description": "An adaptive learning platform for K-12 students that uses gamification to make math and science engaging. We have a working product in two schools and need to scale our tech and sales efforts.",
      "equity_offered": "6-10%",
      "vesting": "4 years, 1 year cliff",
      "funding_raised": "$250K",
      "team_size": 6,
      "revenue": "$12K MRR",
      "looking_for": ["Full-Stack Developer", "Sales Lead", "Data Scientist"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f006",
      "rating": 4.8
    },
    {
      "id": "f007",
      "name": "Olivia Martinez",
      "company": "SaaSify",
      "stage": "Series A",
      "industry": "SaaS",
      "location": "San Francisco, CA",
      "description": "A platform that helps businesses build, manage, and scale their subscription services. We have strong product-market fit and are looking for senior talent to help us expand into enterprise markets.",
      "equity_offered": "1-3%",
      "vesting": "4 years, 1 year cliff",
      "funding_raised": "$5M",
      "team_size": 25,
      "revenue": "$120K MRR",
      "looking_for": ["Senior Product Manager", "Enterprise Sales", "System Architecture"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f007",
      "rating": 4.9
    },
    {
      "id": "f008",
      "name": "Ethan Williams",
      "company": "FitTrack",
      "stage": "Pre-Seed",
      "industry": "HealthTech",
      "location": "Miami, FL",
      "description": "A wearable device and app that provides personalized fitness and nutrition plans based on genetic markers. We have a prototype and need a mobile developer to help us build the user-facing application.",
      "equity_offered": "12-16%",
      "vesting": "3 years, 1 year cliff",
      "funding_raised": "$0",
      "team_size": 3,
      "revenue": "Pre-revenue",
      "looking_for": ["React Native Developer", "UX Designer", "ML Specialist"],
      "verified": false,
      "avatar": "https://i.pravatar.cc/150?u=f008",
      "rating": 4.3
    },
    {
      "id": "f009",
      "name": "Ava Garcia",
      "company": "CarbonZero",
      "stage": "Seed",
      "industry": "GreenTech",
      "location": "Boulder, CO",
      "description": "A B2B platform that helps companies track and offset their carbon emissions. We have a few pilot customers and need a full-stack engineer to improve our dashboard and reporting features.",
      "equity_offered": "7-11%",
      "vesting": "4 years, 1 year cliff",
      "funding_raised": "$300K",
      "team_size": 5,
      "revenue": "$5K MRR",
      "looking_for": ["Full-Stack Developer", "Data Scientist", "Business Development"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f009",
      "rating": 4.6
    },
    {
      "id": "f010",
      "name": "Noah Brown",
      "company": "Insight AI",
      "stage": "Pre-Seed",
      "industry": "AI/ML",
      "location": "Remote",
      "description": "An AI tool that analyzes customer feedback from multiple channels (reviews, support tickets, social media) to provide actionable product insights. Seeking a technical co-founder to build out the backend.",
      "equity_offered": "20-25%",
      "vesting": "4 years, 1 year cliff",
      "funding_raised": "$10K (self-funded)",
      "team_size": 1,
      "revenue": "Pre-revenue",
      "looking_for": ["CTO", "ML Specialist", "Python"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f010",
      "rating": 4.7
    },
    {
      "id": "f011",
      "name": "Liam Davis",
      "company": "Connective",
      "stage": "Seed",
      "industry": "SaaS",
      "location": "Chicago, IL",
      "description": "A project management tool designed for creative agencies. Our unique selling point is our visual-first interface. We need a product manager to help us define our roadmap and prioritize features.",
      "equity_offered": "4-6%",
      "vesting": "4 years, 1 year cliff",
      "funding_raised": "$750K",
      "team_size": 8,
      "revenue": "$20K MRR",
      "looking_for": ["Product Manager", "React", "Node.js"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f011",
      "rating": 4.8
    },
    {
      "id": "f012",
      "name": "Sophia Miller",
      "company": "NextGen Bank",
      "stage": "Series A",
      "industry": "FinTech",
      "location": "New York, NY",
      "description": "A fully digital bank for freelancers and gig economy workers. We have over 10,000 users and are expanding our product offerings. Looking for a security expert to join our team.",
      "equity_offered": "2-4%",
      "vesting": "4 years, 1 year cliff",
      "funding_raised": "$8M",
      "team_size": 35,
      "revenue": "$150K MRR",
      "looking_for": ["Security", "DevOps", "System Architecture"],
      "verified": true,
      "avatar": "https://i.pravatar.cc/150?u=f012",
      "rating": 4.9
    }
];

export const CURRENT_PROFESSIONAL: ProfessionalProfile = {
    "id": "p001",
    "name": "Alex Rodriguez",
    "title": "Senior Full-Stack Developer",
    "experience": "8 years",
    "location": "Remote (Tulsa-based)",
    "skills": ["React", "Node.js", "Python", "AWS", "PostgreSQL", "System Architecture"],
    "industries": ["FinTech", "HealthTech", "SaaS"],
    "rate": "Equity + $50/hr part-time",
    "availability": "20 hrs/week",
    "description": "Experienced full-stack developer with a background in fintech. I have successfully built and launched three SaaS products from scratch. I am looking for a meaningful equity partnership where I can make a significant technical impact.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p001",
    "rating": 4.7,
    "completed_projects": 12,
    "profileCompletion": 94,
    "status": "Actively Looking",
    "desired_equity": "5-10%"
};


export const DUMMY_PROFESSIONALS: ProfessionalProfile[] = [
  CURRENT_PROFESSIONAL,
  {
    "id": "p002",
    "name": "Jennifer Kim",
    "title": "Marketing Director",
    "experience": "10 years",
    "location": "Tulsa, OK",
    "skills": ["Digital Marketing", "Brand Strategy", "Growth Hacking", "Analytics", "Content Strategy"],
    "industries": ["B2B SaaS", "Consumer Tech", "E-commerce"],
    "rate": "Equity only",
    "availability": "30 hrs/week",
    "description": "A growth marketing expert who has scaled two startups from 0 to over $1M ARR. I specialize in creating data-driven marketing strategies for early-stage companies. Seeking an equity-only partnership with high-growth potential.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p002",
    "rating": 4.9,
    "completed_projects": 8,
    "profileCompletion": 88,
    "status": "Actively Looking",
    "desired_equity": "8-12%"
  },
  {
    "id": "p003",
    "name": "David Thompson",
    "title": "Fractional CTO",
    "experience": "15 years",
    "location": "Oklahoma City, OK",
    "skills": ["System Architecture", "Team Leadership", "DevOps", "Security", "Scalability"],
    "industries": ["Enterprise Software", "AI/ML", "Cybersecurity"],
    "rate": "2-5% equity + advisory fee",
    "availability": "15 hrs/week",
    "description": "Former CTO with two successful exits. I specialize in helping early-stage startups build scalable and secure technology foundations. I provide strategic guidance and technical leadership on a fractional basis.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p003",
    "rating": 5.0,
    "completed_projects": 15,
    "profileCompletion": 98,
    "status": "Open to Offers",
    "desired_equity": "2-5% (Advisory)"
  },
   {
    "id": "p004",
    "name": "Maria Rodriguez",
    "title": "VP of Marketing",
    "experience": "12 years",
    "location": "Miami, FL",
    "skills": ["SEO", "PPC", "Content Marketing", "Social Media", "VP Marketing"],
    "industries": ["E-commerce", "SaaS", "HealthTech"],
    "rate": "Equity Only",
    "availability": "25 hrs/week",
    "description": "Seasoned marketing leader with a track record of driving exponential user growth for early-stage ventures.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p004",
    "rating": 4.9,
    "completed_projects": 10,
    "profileCompletion": 92,
    "status": "Actively Looking",
    "desired_equity": "8-12%"
  },
  {
    "id": "p005",
    "name": "Michael Chen",
    "title": "Senior Product Manager",
    "experience": "7 years",
    "location": "Austin, TX",
    "skills": ["Agile", "Roadmapping", "User Research", "A/B Testing", "Product Manager"],
    "industries": ["FinTech", "EdTech", "SaaS"],
    "rate": "Equity + Stipend",
    "availability": "30 hrs/week",
    "description": "Product leader focused on building user-centric products that achieve product-market fit. Experienced in both B2B and B2C.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p005",
    "rating": 4.8,
    "completed_projects": 9,
    "profileCompletion": 95,
    "status": "Open to Offers",
    "desired_equity": "4-7%"
  },
  {
    "id": "p006",
    "name": "Emily White",
    "title": "Lead UX/UI Designer",
    "experience": "6 years",
    "location": "Remote",
    "skills": ["Figma", "Sketch", "Prototyping", "Design Systems", "UX Designer"],
    "industries": ["HealthTech", "GreenTech", "E-commerce"],
    "rate": "Equity Only",
    "availability": "20 hrs/week",
    "description": "Designs beautiful and intuitive interfaces that solve complex user problems. Passionate about creating accessible products.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p006",
    "rating": 4.9,
    "completed_projects": 14,
    "profileCompletion": 90,
    "status": "Actively Looking",
    "desired_equity": "6-10%"
  },
  {
    "id": "p007",
    "name": "Daniel Park",
    "title": "Data Scientist",
    "experience": "5 years",
    "location": "San Francisco, CA",
    "skills": ["Python", "R", "TensorFlow", "Scikit-learn", "ML Specialist", "Data Scientist"],
    "industries": ["AI/ML", "FinTech", "HealthTech"],
    "rate": "Equity + Stipend",
    "availability": "15 hrs/week",
    "description": "Specializes in building machine learning models that extract actionable insights from complex datasets.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p007",
    "rating": 4.7,
    "completed_projects": 6,
    "profileCompletion": 85,
    "status": "Open to Offers",
    "desired_equity": "7-11%"
  },
  {
    "id": "p008",
    "name": "Jessica Taylor",
    "title": "Sales Lead",
    "experience": "8 years",
    "location": "Chicago, IL",
    "skills": ["B2B Sales", "Lead Generation", "CRM", "Negotiation", "Sales Lead"],
    "industries": ["SaaS", "GreenTech", "EdTech"],
    "rate": "Equity + Commission",
    "availability": "Full-time",
    "description": "Expert in building sales pipelines from the ground up and closing deals in competitive B2B markets.",
    "verified": false,
    "avatar": "https://i.pravatar.cc/150?u=p008",
    "rating": 4.6,
    "completed_projects": 25,
    "profileCompletion": 78,
    "status": "Actively Looking",
    "desired_equity": "5-8%"
  },
  {
    "id": "p009",
    "name": "Kevin Brown",
    "title": "DevOps Engineer",
    "experience": "9 years",
    "location": "Remote",
    "skills": ["AWS", "Docker", "Kubernetes", "CI/CD", "DevOps"],
    "industries": ["SaaS", "FinTech", "AI/ML"],
    "rate": "Equity + Stipend",
    "availability": "20 hrs/week",
    "description": "Automates and streamlines development pipelines to ensure scalable, reliable, and efficient software delivery.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p009",
    "rating": 4.8,
    "completed_projects": 11,
    "profileCompletion": 96,
    "status": "Open to Offers",
    "desired_equity": "3-6%"
  },
  {
    "id": "p010",
    "name": "Laura Wilson",
    "title": "React Native Developer",
    "experience": "4 years",
    "location": "Portland, OR",
    "skills": ["React Native", "iOS", "Android", "GraphQL"],
    "industries": ["HealthTech", "E-commerce", "Consumer Tech"],
    "rate": "Equity only",
    "availability": "30 hrs/week",
    "description": "Builds cross-platform mobile applications with a focus on smooth performance and excellent user experience.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p010",
    "rating": 4.7,
    "completed_projects": 7,
    "profileCompletion": 89,
    "status": "Actively Looking",
    "desired_equity": "8-12%"
  },
  {
    "id": "p011",
    "name": "Chris Martinez",
    "title": "Smart Contract Developer",
    "experience": "5 years",
    "location": "Remote",
    "skills": ["Solidity", "Ethereum", "Web3.js", "Hardhat", "Smart Contract Developer"],
    "industries": ["FinTech", "DeFi", "Blockchain"],
    "rate": "Equity only",
    "availability": "25 hrs/week",
    "description": "Specializes in writing secure and efficient smart contracts for decentralized applications on the Ethereum blockchain.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p011",
    "rating": 4.9,
    "completed_projects": 9,
    "profileCompletion": 93,
    "status": "Actively Looking",
    "desired_equity": "10-15%"
  },
  {
    "id": "p012",
    "name": "Sarah Adams",
    "title": "Business Development Manager",
    "experience": "7 years",
    "location": "New York, NY",
    "skills": ["Strategic Partnerships", "Market Research", "Sales Strategy", "Business Development"],
    "industries": ["GreenTech", "EdTech", "SaaS"],
    "rate": "Equity + Commission",
    "availability": "Full-time",
    "description": "Identifies and develops strategic partnerships to drive revenue growth and market expansion.",
    "verified": false,
    "avatar": "https://i.pravatar.cc/150?u=p012",
    "rating": 4.5,
    "completed_projects": 18,
    "profileCompletion": 82,
    "status": "Open to Offers",
    "desired_equity": "6-9%"
  },
  {
    "id": "p013",
    "name": "Brian Clark",
    "title": "Full-Stack Developer",
    "experience": "6 years",
    "location": "Boulder, CO",
    "skills": ["React", "Vue.js", "Django", "Flask", "Full-Stack Developer"],
    "industries": ["EdTech", "E-commerce", "GreenTech"],
    "rate": "Equity + Stipend",
    "availability": "35 hrs/week",
    "description": "Versatile developer proficient in both front-end and back-end technologies, capable of building features from concept to deployment.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p013",
    "rating": 4.6,
    "completed_projects": 10,
    "profileCompletion": 91,
    "status": "Not Looking",
    "desired_equity": "5-8%"
  },
  {
    "id": "p014",
    "name": "Karen Lewis",
    "title": "Regulatory Consultant",
    "experience": "18 years",
    "location": "Washington D.C.",
    "skills": ["HIPAA", "FDA Compliance", "Healthcare Law", "Regulatory Consultant"],
    "industries": ["HealthTech"],
    "rate": "Advisory Equity",
    "availability": "5-10 hrs/week",
    "description": "Former regulator providing expert guidance on navigating the complex compliance landscape for HealthTech startups.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p014",
    "rating": 5.0,
    "completed_projects": 22,
    "profileCompletion": 99,
    "status": "Open to Offers",
    "desired_equity": "2-4% (Advisory)"
  },
  {
    "id": "p015",
    "name": "Tom Harris",
    "title": "Head of Content Strategy",
    "experience": "9 years",
    "location": "Remote",
    "skills": ["SEO", "Copywriting", "Brand Voice", "Content Strategy"],
    "industries": ["E-commerce", "SaaS", "EdTech"],
    "rate": "Equity only",
    "availability": "20 hrs/week",
    "description": "Develops and executes content strategies that build brand authority, attract organic traffic, and convert users.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p015",
    "rating": 4.8,
    "completed_projects": 13,
    "profileCompletion": 88,
    "status": "Actively Looking",
    "desired_equity": "7-10%"
  },
  {
    "id": "p016",
    "name": "Nancy Scott",
    "title": "Enterprise Sales Director",
    "experience": "14 years",
    "location": "San Francisco, CA",
    "skills": ["Enterprise Sales", "SaaS Sales", "Negotiation"],
    "industries": ["SaaS", "Enterprise Software"],
    "rate": "Equity + Commission",
    "availability": "Full-time",
    "description": "Specializes in closing high-ticket deals with Fortune 500 companies. Proven track record of exceeding sales quotas.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p016",
    "rating": 4.9,
    "completed_projects": 30,
    "profileCompletion": 94,
    "status": "Open to Offers",
    "desired_equity": "2-4%"
  },
  {
    "id": "p017",
    "name": "Steven Walker",
    "title": "Python Developer",
    "experience": "7 years",
    "location": "Remote",
    "skills": ["Python", "Django", "FastAPI", "ML Specialist"],
    "industries": ["AI/ML", "FinTech"],
    "rate": "Equity + Stipend",
    "availability": "30 hrs/week",
    "description": "Backend developer with deep expertise in Python frameworks and building AI-driven applications.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p017",
    "rating": 4.7,
    "completed_projects": 8,
    "profileCompletion": 90,
    "status": "Actively Looking",
    "desired_equity": "8-12%"
  },
  {
    "id": "p018",
    "name": "Rachel Green",
    "title": "QA Engineer",
    "experience": "5 years",
    "location": "Raleigh, NC",
    "skills": ["Selenium", "Cypress", "Test Planning", "Automation"],
    "industries": ["FinTech", "SaaS", "E-commerce"],
    "rate": "Equity only",
    "availability": "20 hrs/week",
    "description": "Meticulous QA engineer focused on test automation to ensure product quality and a bug-free user experience.",
    "verified": false,
    "avatar": "https://i.pravatar.cc/150?u=p018",
    "rating": 4.4,
    "completed_projects": 15,
    "profileCompletion": 81,
    "status": "Open to Offers",
    "desired_equity": "3-5%"
  },
  {
    "id": "p019",
    "name": "Paul Young",
    "title": "Technical Project Manager",
    "experience": "10 years",
    "location": "Remote",
    "skills": ["Scrum", "Kanban", "JIRA", "Project Planning"],
    "industries": ["HealthTech", "EdTech", "SaaS"],
    "rate": "Equity + Stipend",
    "availability": "25 hrs/week",
    "description": "Organizes complex technical projects, manages timelines, and ensures engineering teams deliver on schedule.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p019",
    "rating": 4.8,
    "completed_projects": 16,
    "profileCompletion": 93,
    "status": "Actively Looking",
    "desired_equity": "4-6%"
  },
  {
    "id": "p020",
    "name": "Olivia King",
    "title": "Cybersecurity Specialist",
    "experience": "8 years",
    "location": "New York, NY",
    "skills": ["Penetration Testing", "Network Security", "Compliance", "Security"],
    "industries": ["FinTech", "Enterprise Software", "HealthTech"],
    "rate": "Equity + Stipend",
    "availability": "15 hrs/week",
    "description": "Protects digital assets and user data by identifying vulnerabilities and implementing robust security protocols.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p020",
    "rating": 4.9,
    "completed_projects": 11,
    "profileCompletion": 97,
    "status": "Open to Offers",
    "desired_equity": "5-8%"
  },
  {
    "id": "p021",
    "name": "Andrew Wright",
    "title": "Data Analyst",
    "experience": "4 years",
    "location": "Remote",
    "skills": ["SQL", "Tableau", "Power BI", "Data Visualization"],
    "industries": ["E-commerce", "GreenTech", "SaaS"],
    "rate": "Equity only",
    "availability": "20 hrs/week",
    "description": "Translates raw data into clear, actionable insights through dashboards and reports to guide business strategy.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p021",
    "rating": 4.6,
    "completed_projects": 9,
    "profileCompletion": 84,
    "status": "Actively Looking",
    "desired_equity": "4-7%"
  },
  {
    "id": "p022",
    "name": "Diana Hill",
    "title": "System Architecture Consultant",
    "experience": "16 years",
    "location": "Remote",
    "skills": ["System Architecture", "Microservices", "Scalability", "Cloud"],
    "industries": ["SaaS", "AI/ML", "FinTech"],
    "rate": "Advisory Equity",
    "availability": "10 hrs/week",
    "description": "Designs high-level structure for software systems, ensuring they are scalable, resilient, and maintainable for long-term growth.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p022",
    "rating": 5.0,
    "completed_projects": 25,
    "profileCompletion": 99,
    "status": "Open to Offers",
    "desired_equity": "3-5% (Advisory)"
  },
  {
    "id": "p023",
    "name": "Mark Roberts",
    "title": "iOS Developer",
    "experience": "7 years",
    "location": "San Diego, CA",
    "skills": ["Swift", "SwiftUI", "Objective-C", "Core Data", "iOS"],
    "industries": ["HealthTech", "E-commerce", "Consumer Tech"],
    "rate": "Equity + Stipend",
    "availability": "30 hrs/week",
    "description": "Dedicated iOS engineer building polished, high-performance native applications for Apple's ecosystem.",
    "verified": true,
    "avatar": "https://i.pravatar.cc/150?u=p023",
    "rating": 4.8,
    "completed_projects": 12,
    "profileCompletion": 92,
    "status": "Not Looking",
    "desired_equity": "6-9%"
  }
];

export const DUMMY_PROJECTS: Project[] = [
  {
    id: 1,
    name: 'FinTech Disruptor App',
    founder: 'Alex Johnson',
    status: 'Contract Secured',
    equity: 2.5,
    vestingYears: 4,
    vestingStartDate: new Date('2023-01-15'),
    description: 'A next-generation mobile banking application aimed at simplifying personal finance for millennials through AI-driven insights and gamified savings goals.',
    kpis: [
        { name: 'User Signups (Target)', value: '10,000 / 25,000' },
        { name: 'App Store Rating', value: '4.8 Stars' },
    ],
  },
  {
    id: 2,
    name: 'HealthTech Wearable OS',
    founder: 'Samantha Lee',
    status: 'Milestone Pending',
    equity: 3.0,
    vestingYears: 4,
    vestingStartDate: new Date('2023-09-01'),
    description: 'Developing a proprietary operating system for a new line of health-monitoring wearables, focusing on real-time data analysis and preventative health alerts.',
    kpis: [
        { name: 'Prototype Accuracy', value: '98.5%' },
        { name: 'Target Battery Life', value: '72 Hours' },
    ],
  },
];

export const DUMMY_APPLICATIONS: Application[] = [
    { id: 1, company: 'TechFlow AI', role: 'Lead Engineer', stage: 'Technical Interview', equity: '15-20%', appliedDate: '2024-07-20' },
    { id: 2, company: 'EcoLogistics', role: 'Technical Advisor', stage: 'Contract Review', equity: '2-3%', appliedDate: '2024-07-18' },
    { id: 3, company: 'MedConnect', role: 'Full-Stack Developer', stage: 'Initial Screening', equity: '8-12%', appliedDate: '2024-07-15' },
];

export const DUMMY_ACTIVITY: ActivityLog[] = [
    { id: 1, actor: 'Sarah Chen', action: 'viewed', target: 'your profile', timestamp: '2 hours ago', avatar: 'https://i.pravatar.cc/150?u=f001' },
    { id: 2, actor: 'You', action: 'sent', target: 'application to TechFlow AI', timestamp: '1 day ago', avatar: 'https://i.pravatar.cc/150?u=p001' },
    { id: 3, actor: 'Marcus Johnson', action: 'viewed', target: 'your profile', timestamp: '3 days ago', avatar: 'https://i.pravatar.cc/150?u=f002' },
];

export const DUMMY_INCOMING_MESSAGES: Message[] = [
    { id: 1, partnerName: 'Sarah Chen', snippet: "Hi Alex, thanks for applying. Your profile looks great...", timestamp: '1 day ago', status: 'Unread', avatar: 'https://i.pravatar.cc/150?u=f001' },
    { id: 2, partnerName: 'Marcus Johnson', snippet: "Following up on our conversation last week...", timestamp: '4 days ago', status: 'Read', avatar: 'https://i.pravatar.cc/150?u=f002' },
];

export const DUMMY_SENT_MESSAGES: Message[] = [
    { id: 1, partnerName: 'Dr. Priya Patel', snippet: "Hello Dr. Patel, I'm very interested in the Full-Stack role...", timestamp: '6 days ago', status: 'Read', avatar: 'https://i.pravatar.cc/150?u=f003' },
];

export const DUMMY_GOVERNANCE_LOGS: GovernanceLog[] = [
  { id: 1, timestamp: '2024-07-21 14:30:15', event: 'New Verified Partner Onboarded: Mark Chen', type: 'success' },
  { id: 2, timestamp: '2024-07-21 13:05:00', event: 'IP Assignment Confirmed for Project #1', type: 'info' },
  { id: 3, timestamp: '2024-07-20 18:00:22', event: 'Vesting Cliff Met: Jane Doe (Project #1)', type: 'success' },
  { id: 4, timestamp: '2024-07-20 11:45:10', event: 'EFS Contract Executed: FinTech Disruptor App', type: 'info' },
  { id: 5, timestamp: '2024-07-19 09:00:00', event: 'New Verified Partner Onboarded: Jane Doe', type: 'success' },
];

export const DUMMY_FOUNDER_GOVERNANCE_LOGS: GovernanceLog[] = [
  { id: 1, timestamp: '2024-07-22 10:00:00', event: "Milestone 'MVP Backend' for Project Roadmap approved.", type: 'success' },
  { id: 2, timestamp: '2024-07-21 14:30:15', event: 'Contract with professional Alex Rodriguez executed.', type: 'info' },
  { id: 3, timestamp: '2024-07-20 09:00:00', event: 'Alex Rodriguez met 1-year vesting cliff.', type: 'success' },
  { id: 4, timestamp: '2024-07-18 17:21:05', event: 'Funds for Q3 operational budget deposited.', type: 'info' },
  { id: 5, timestamp: '2024-07-15 11:00:00', event: 'Action required: Review updated terms of service.', type: 'warning' },
];

export const DUMMY_USERS: User[] = [
  {
    id: 101,
    name: 'Alex Johnson',
    email: 'alex.j@fintechdisrupt.com',
    role: 'Founder',
    status: 'Active',
    registeredDate: '2023-01-10',
  },
  {
    id: 102,
    name: 'Samantha Lee',
    email: 's.lee@healthwear.io',
    role: 'Founder',
    status: 'Active',
    registeredDate: '2023-08-20',
  },
  {
    id: 1, // Matches ProfessionalProfile for consistency
    name: 'Jane Doe',
    email: 'jane.d@email.com',
    role: 'Professional',
    status: 'Active',
    registeredDate: '2022-11-05',
  },
  {
    id: 2, // Matches ProfessionalProfile
    name: 'Mark Chen',
    email: 'mark.chen@design.co',
    role: 'Professional',
    status: 'Inactive',
    registeredDate: '2023-02-15',
  },
  {
    id: 3, // Matches ProfessionalProfile
    name: 'Samuel Jones',
    email: 'sam.jones@cloudarch.net',
    role: 'Professional',
    status: 'Active',
    registeredDate: '2023-05-30',
  },
  {
    id: 103,
    name: 'Priya Singh',
    email: 'priya.s@aimarketing.ai',
    role: 'Founder',
    status: 'Active',
    registeredDate: '2024-06-12',
  },
];

export const DUMMY_CONTRACTS: Contract[] = [
  {
    id: 1,
    projectName: 'FinTech Disruptor App',
    founderName: 'Alex Johnson',
    professionalName: 'Jane Doe',
    equityPercentage: 2.5,
    status: 'Executed',
    executionDate: '2024-07-20',
  },
  {
    id: 2,
    projectName: 'HealthTech Wearable OS',
    founderName: 'Samantha Lee',
    professionalName: 'Mark Chen',
    equityPercentage: 3.0,
    status: 'Executed',
    executionDate: '2024-06-15',
  },
  {
    id: 3,
    projectName: 'AI Marketing Bot',
    founderName: 'Priya Singh',
    professionalName: 'Samuel Jones',
    equityPercentage: 1.75,
    status: 'Pending Review',
    executionDate: '2024-07-22',
  },
  {
    id: 4,
    projectName: 'Eco-Friendly Logistics Platform',
    founderName: 'Alex Johnson',
    professionalName: 'Samuel Jones',
    equityPercentage: 2.0,
    status: 'Executed',
    executionDate: '2024-05-10',
  },
  {
    id: 5,
    projectName: 'Project Phoenix',
    founderName: 'Samantha Lee',
    professionalName: 'Jane Doe',
    equityPercentage: 4.0,
    status: 'Completed',
    executionDate: '2023-01-01',
  }
];

export const DUMMY_COMPANY_PROFILE: CompanyProfile = {
    id: 'c001',
    name: 'TechFlow AI',
    requiredHires: [
        { role: 'CTO / Lead Engineer', skills: ['ML Specialist', 'System Architecture', 'Python'] },
        { role: 'VP Marketing', skills: ['Growth Hacking', 'Brand Strategy'] },
        { role: 'UX Designer', skills: ['Figma', 'User Research'] },
    ],
    equityDistribution: {
        founders: 70,
        esop: 20,
        investors: 10,
    },
    budgetMode: false,
    contractsOnboarded: 5,
};

export const DUMMY_ROADMAP: RoadmapPhase[] = [
    {
        id: 'phase1',
        name: 'Discovery & Validation',
        duration: 'Q3 2024',
        requiredSkills: ['User Research', 'Market Analysis'],
        hiringProgress: { needed: 1, matched: 1 },
        status: 'completed',
    },
    {
        id: 'phase2',
        name: 'MVP Development',
        duration: 'Q4 2024',
        requiredSkills: ['React', 'Node.js', 'ML Specialist', 'System Architecture'],
        hiringProgress: { needed: 2, matched: 1 },
        status: 'inprogress',
    },
    {
        id: 'phase3',
        name: 'Beta Launch',
        duration: 'Q1 2025',
        requiredSkills: ['Growth Hacking', 'QA Testing'],
        hiringProgress: { needed: 2, matched: 0 },
        status: 'todo',
    },
     {
        id: 'phase4',
        name: 'Growth & Scaling',
        duration: 'Q2 2025',
        requiredSkills: ['DevOps', 'Brand Strategy', 'Data Analytics'],
        hiringProgress: { needed: 3, matched: 0 },
        status: 'todo',
    }
];


export const NEW_LOG_TEMPLATES: Array<{ event: string; type: GovernanceLog['type'] }> = [
  { event: 'Milestone Approved: HealthTech Wearable OS', type: 'success' },
  { event: 'Dispute Flagged: Project #3 - Review needed', type: 'warning' },
  { event: 'New EFS Contract Executed: AI Marketing Bot', type: 'info' },
  { event: 'Payment Processed for Transaction #4561', type: 'info' },
  { event: 'New Verified Partner Onboarded: Priya Singh', type: 'success' },
  { event: 'Security Audit Passed for v2.1.0', type: 'info' },
  { event: 'Equity Vesting Confirmed: Mark Chen (Project #2)', type: 'success' },
];

export const LEGAL_CLAUSE = `The Professional hereby agrees to irrevocably assign, transfer, and convey to the Company all right, title, and interest in and to any and all Intellectual Property conceived, reduced to practice, or developed by the Professional during the term of this Agreement and related to the Company’s business.`;

export const SURVEY_QUESTIONS: SurveyQuestion[] = [
    {
        id: 'f1',
        type: 'founder',
        question: "What is your BIGGEST fear when giving away equity for services?",
        options: [
            "Giving away too much equity",
            "The partner not delivering",
            "Complex and expensive legal contracts",
            "IP not being properly assigned to the company"
        ]
    },
    {
        id: 'p1',
        type: 'professional',
        question: "What is your BIGGEST fear when accepting equity for your services?",
        options: [
            "The equity becoming worthless",
            "The founder changing the deal later",
            "Not having a clear, secure legal agreement",
            "My contributions and IP not being recognized"
        ]
    }
];

export const CONTRACT_TEMPLATES: ContractTemplate[] = [
    {
        id: 'std-efs',
        name: 'Standard EFS Agreement',
        description: 'A foundational Equity-for-Services contract covering essential terms, vesting schedules, and IP assignment. Ideal for early-stage partnerships.',
        price: null,
        category: 'Standard',
        legalText: `This Equity-for-Services Agreement ("Agreement") is made between the Company and the Professional. The Professional will perform services in exchange for an equity grant of [X]% subject to a [Y]-year vesting schedule with a 1-year cliff. All intellectual property created by the Professional under this Agreement shall be the sole property of the Company.`
    },
    {
        id: 'std-nda',
        name: 'Standard Mutual NDA',
        description: 'A non-disclosure agreement to protect confidential information shared between both parties during initial discussions and project collaboration.',
        price: null,
        category: 'Standard',
        legalText: `The parties agree to hold in confidence all proprietary information disclosed during the course of their discussions. This obligation extends for a period of three (3) years from the date of disclosure. Unauthorized use or disclosure of confidential information is strictly prohibited.`
    },
    {
        id: 'prem-efs',
        name: 'Premium EFS Agreement',
        description: 'An advanced EFS agreement with detailed milestone-based vesting, performance clauses, and specific IP protections for high-stakes projects.',
        price: 250,
        category: 'Premium',
        legalText: `In addition to standard terms, this Premium Agreement includes performance-based vesting triggers tied to specific Key Performance Indicators (KPIs) as defined in Exhibit A. Failure to meet KPIs may result in an adjustment of the equity grant. This agreement also includes a right of first refusal for the Company on future services provided by the Professional.`
    },
    {
        id: 'prem-gov',
        name: 'Premium Governance Contract',
        description: 'Includes automated milestone tracking, escrow for equity, and access to a streamlined dispute resolution process to ensure accountability.',
        price: 500,
        category: 'Premium',
        legalText: `This Governance Contract establishes a framework for automated equity release upon verified completion of milestones. All equity shall be held in escrow by SPYN and released algorithmically. Any disputes arising from milestone verification shall be submitted to SPYN's binding arbitration process.`
    }
];

export const EFS_WORKFLOW_STEPS = [
  {
    title: "1. AI-Powered Match",
    description: "Founders define needs, professionals showcase skills. Our AI analyzes compatibility for the perfect fit, ensuring alignment on vision, skills, and risk tolerance.",
  },
  {
    title: "2. On-Platform Legal Transaction",
    description: "Select, customize, and execute legally-vetted Equity-for-Services contracts directly on the platform. Eliminate ambiguity and costly legal fees.",
  },
  {
    title: "3. Automated Governance",
    description: "Link project milestones to automated equity vesting and IP assignment. Our platform provides a transparent, secure record of all contributions and transactions.",
  }
];

export const PRICING_FAQS = [
    {
        question: "What is the SPYN Transaction Fee?",
        answer: "SPYN charges a small 2.5% success fee based on the total equity value of a Premium EFS contract upon its successful execution. This fee aligns our success with yours. There are no fees for Standard contracts or for simply connecting on the platform."
    },
    {
        question: "Why is the Founder plan monthly and the Professional plan yearly?",
        answer: "Founder needs are often project-based and intensive during the hiring phase, making a monthly subscription more flexible. Professionals benefit from a yearly plan that establishes their verified status and credibility in the marketplace for the long term."
    },
    {
        question: "What does being 'SPYN Certified' involve?",
        answer: "Our certification process involves a review of your professional history, key skills, and references. This verification helps you stand out to high-quality founders and builds a foundation of trust, leading to better partnership opportunities."
    },
    {
        question: "Can I cancel my subscription at any time?",
        answer: "Yes, you can cancel your subscription at any time. For monthly plans, your access will continue until the end of the current billing period. For yearly plans, access will continue until the end of the one-year term."
    }
];
